apiVersion: v1
kind: Secret
metadata:
  name: cluster-api-secret
type: Opaque
data:
  # you can get your personal accesskey and secret key from https://console.bce.baidu.com/iam/?locale=zh-cn#/iam/accesslist
  # please keep them hidden and leak them to others
  AccessKeyID: ''
  SecretAccessKey: ''
  Region: ''