apiVersion: cluster.k8s.io/v1alpha1
kind: Machine
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: machine-sample-master
spec:
  providerSpec:
    value:
      apiVersion: "cceproviderconfig/v1alpha1"
      kind: "CCEMachineProviderConfig"
      clusterName: "cluster-test3"
      role: "master"
      adminPass: "testpw123!"
      imageId: "m-8WV4kRlN" # ubuntu 16.04 lts amd64
      cpuCount: 2
      memoryCapacityInGB: 2
  versions:
    kubelet: 1.12.3
    controlPlane: 1.12.3
---
apiVersion: cluster.k8s.io/v1alpha1
kind: Machine
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: machine-sample-node
spec:
  providerSpec:
    value:
      apiVersion: "cceproviderconfig/v1alpha1"
      kind: "CCEMachineProviderConfig"
      clusterName: "cluster-test3"
      role: "node"
      adminPass: "testpw123!"
      imageId: "m-8WV4kRlN"
      cpuCount: 2
      memoryCapacityInGB: 2
  versions:
    kubelet: 1.12.3
    controlPlane: 1.12.3
